### ISSUE TITLE
Document files with spaces not found

### ISSUE THREAD

**Issue by ptoews** [rjoberon/bibsonomy-ruby#2]
Hey @rjoberon,

we experience an issue where this gem fails to download documents that contain spaces in their names. I could reproduce this with a direct call to BibSonomy::APIs `get_document()` method. The response body contains the error message "can't find document". I used some debug prints to find out that the final API request URL uses '+' signs to encode space characters, while the actual file URL opened in the browser has '%20' sequences for the spaces. Could this be the cause of this error?

**Comment by rjoberon** [comment]
Yes, that was very likely the problem. This should be fixed now by proper encoding the URL.

**Comment by ptoews** [comment]
Great, thanks!
